# Generated by Django 3.2.3 on 2021-06-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_woker', models.CharField(max_length=50, null=True)),
                ('b_work', models.CharField(max_length=50, null=True)),
                ('b_Owner', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('O_name', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=15, null=True)),
                ('adhar_no', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Name_worker', models.CharField(max_length=20, null=True)),
                ('adhar_no', models.CharField(max_length=16, null=True)),
                ('age', models.CharField(max_length=3, null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(choices=[('select_status', '--Select status--'), ('YES', 'YES'), ('NO', 'NO')], default='', help_text='status', max_length=50, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('language', models.CharField(choices=[('select_status', '--Select status--'), ('HINDI', 'HINDI'), ('ENGLISH', 'ENGLISH'), ('PUNJABI', 'PUNJABI'), ('Other', 'Other')], default='', help_text='status', max_length=50, null=True)),
                ('charge_per_day', models.CharField(max_length=10, null=True)),
                ('Type_of_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.work')),
            ],
        ),
        migrations.CreateModel(
            name='Owner_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_dec', models.CharField(max_length=50)),
                ('pay_for_work', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.owner')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.work')),
            ],
        ),
    ]
