# Generated by Django 3.2.3 on 2021-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='action',
            field=models.CharField(choices=[('select_status', '--Select status--'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='', help_text='status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='b_woker_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
