# Generated by Django 3.2.3 on 2021-06-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_work',
            name='work_type',
            field=models.CharField(max_length=100),
        ),
    ]
