# Generated by Django 3.2.3 on 2021-06-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_owner_work_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='b_Owner',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='b_woker',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='b_work',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
