# Generated by Django 3.2.3 on 2021-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210614_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
