# Generated by Django 3.2 on 2023-07-25 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_clienttestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_work',
            name='applicants_needed',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('B', 'Both')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='owner_work',
            name='deadline',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='owner_work',
            name='experience_level',
            field=models.CharField(choices=[('JUN', 'Junior'), ('MID', 'Mid Level'), ('SEN', 'Senior')], default='JUN', max_length=3),
        ),
        migrations.AddField(
            model_name='owner_work',
            name='vacancies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
